[package]
name = "kociemba-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
kociemba = {path = "../"}
crossterm = "0.27.0"
clap = { version = "4.5.4", features = ["derive"] } 
spinners = "4.1.1"